# Generated by Django 5.0.4 on 2024-09-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
